import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// const poppins = Poppins({subsets:['latin'], weight:['300','400','500','600','700','800','900']});
const poppins = Outfit({subsets:['latin'], });
export const metadata: Metadata = {
  title: "DoChat",
  description: "Generated by DoChat",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased bg-white`}
      >
        <Navbar/>
       <div className="pt-[10%] md:pt-[3%] w-full z-0"> {children}</div>
        <Footer />
      </body>
    </html>
  );
}
